"""Domain-organized schemas with a stable aggregate export."""

from .common import *
from .pixels import *
from .palettes import *
from .documents import *
from .animation import *
from .tiles import *
from .export import *
from .validation import *

__all__ = [
    "StrictModel",
    "HealthResult",
    "ToolCapability",
    "ToolProfileCapability",
    "CapabilitiesResult",
    "PixelRatio",
    "FrameInfo",
    "LayerInfo",
    "TagInfo",
    "RectangleInfo",
    "PointInfo",
    "FloatPointInfo",
    "SliceKeyInfo",
    "SliceInfo",
    "ColorInfo",
    "PaletteInfo",
    "AnimationEventInfo",
    "SpriteInfo",
    "FileResult",
    "RenderResult",
    "SpriteSheetResult",
    "MutationResult",
    "AnimationFrameBounds",
    "AnimationValidationIssue",
    "AnimationValidationResult",
    "PixelInput",
    "PaletteColorInput",
    "PixelRun",
    "PixelRunInput",
    "PixelReadResult",
    "CompositedPixelReadResult",
    "FrameComparisonResult",
    "ContactSheetResult",
    "RectangleInput",
    "PointInput",
    "SliceEditOperation",
    "PropertyEditOperation",
    "TilesetEditOperation",
    "CelDetail",
    "CelInspectionResult",
    "ColorUsage",
    "PaletteAnalysisResult",
    "TilesetDetail",
    "TilesetInspectionResult",
    "TilesetValidationIssue",
    "TilesetValidationResult",
    "ShapeInput",
    "SelectionEditOperation",
    "TilemapCellInput",
    "TilesetExportResult",
    "StrokeInput",
    "PaletteEntryEditOperation",
    "SpriteFrameDifference",
    "SpriteComparisonResult",
    "ExportProfile",
    "ExportProfileIssue",
    "ExportProfileValidationResult",
    "AtlasResult",
    "SliceExtractionInput",
    "SliceExtractionItem",
    "SliceExtractionResult",
    "CollisionRectangle",
    "CollisionFrame",
    "CollisionMaskResult",
    "BatchExportJob",
    "BatchExportItem",
    "BatchExportResult",
    "AssetValidationItem",
    "AssetSetValidationResult",
    "FrameExportInput",
    "FrameExportItem",
    "FrameExportResult",
    "BlendModeEditOperation",
    "AnimationEventEditOperation",
    "CelEditOperation",
    "PixelArtValidationIssue",
    "PixelArtValidationResult",
    "LoopTransitionValidationResult",
    "TileMetadataItem",
    "TileMetadataResult",
    "TileMetadataEditOperation",
    "MotionFrameMetric",
    "MotionReportResult",
    "CollisionPolygon",
    "CollisionPolygonFrame",
    "CollisionPolygonResult",
    "BitmapGlyphInput",
    "BitmapFontResult",
    "FrameEditOperation",
    "LayerEditOperation",
    "TagEditOperation",
    "AnimationCelDefinition",
    "AnimationFrameDefinition",
    "AnimationTagDefinition",
    "LayerDefinition",
    "FrameDefinition",
]
