"""Generate checked-in MCP tool documentation from source and declarative policy."""

from __future__ import annotations

import ast
import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
from aseprite.capabilities import (  # noqa: E402
    PROFILE_ALIASES,
    PROFILE_TOOL_NAMES,
    READ_TOOL_NAMES,
    WRITE_TOOL_NAMES,
    profiles_for_tool,
    tool_policy,
)


def discover_tools(root: Path) -> list[dict[str, object]]:
    """Read tool functions without importing the MCP SDK or Pydantic."""

    entries: list[dict[str, object]] = []
    for path in sorted(root.glob("*.py")):
        if path.stem in {"__init__", "generate_catalog", "inputs"}:
            continue
        tree = ast.parse(path.read_text(encoding="utf-8-sig"), filename=str(path))
        for node in ast.walk(tree):
            if not isinstance(node, ast.AsyncFunctionDef) or not node.name.startswith("aseprite_"):
                continue
            mutability, output, requires_aseprite = tool_policy(node.name)
            entries.append(
                {
                    "name": node.name,
                    "category": path.stem,
                    "profiles": list(profiles_for_tool(node.name)),
                    "mutability": mutability,
                    "output": output,
                    "requires_aseprite": requires_aseprite,
                    "description": ast.get_docstring(node) or "",
                }
            )
    entries.sort(key=lambda item: str(item["name"]))
    names = [str(entry["name"]) for entry in entries]
    if len(names) != len(set(names)):
        raise ValueError("duplicate MCP tool names were discovered")
    policy_names = READ_TOOL_NAMES | WRITE_TOOL_NAMES
    if set(names) != policy_names:
        raise ValueError(
            f"tool policy mismatch: missing={set(names) - policy_names} "
            f"stale={policy_names - set(names)}"
        )
    return entries


def markdown(entries: list[dict[str, object]]) -> str:
    """Render a compact human-readable tool catalog."""

    lines = [
        "# Aseprite MCP tool catalog",
        "",
        "Generated by `python aseprite/tools/generate_catalog.py`. Do not edit manually.",
        "",
        f"Total tools: **{len(entries)}**.",
        "",
        "## Profiles",
        "",
        "| Profile | Categories | Tools |",
        "| --- | --- | ---: |",
    ]
    for profile, tools in PROFILE_TOOL_NAMES.items():
        categories = sorted({
            str(entry["category"]) for entry in entries if entry["name"] in tools
        })
        count = len(tools)
        lines.append(f"| `{profile}` | {', '.join(sorted(categories))} | {count} |")
    lines.extend(["", "Legacy aliases: " + ", ".join(
        f"`{alias}` → `{target}`" for alias, target in PROFILE_ALIASES.items()
    ) + "."])
    for category in sorted({str(entry["category"]) for entry in entries}):
        lines.extend(
            [
                "",
                f"## {category.title()}",
                "",
                "| Tool | Access | Output | Aseprite | Description |",
                "| --- | --- | --- | --- | --- |",
            ]
        )
        for entry in entries:
            if entry["category"] != category:
                continue
            description = str(entry["description"]).replace("|", "\\|").replace("\n", " ")
            requires = "required" if entry["requires_aseprite"] else "not required"
            lines.append(
                f"| `{entry['name']}` | {entry['mutability']} | {entry['output']} | "
                f"{requires} | {description} |"
            )
    return "\n".join(lines) + "\n"


def main() -> None:
    root = Path(__file__).resolve().parent
    entries = discover_tools(root)
    profiles = [
        {
            "name": profile,
            "categories": sorted(categories),
            "tool_count": len(tools),
        }
        for profile, tools in PROFILE_TOOL_NAMES.items()
        for categories in [{
            str(entry["category"]) for entry in entries if entry["name"] in tools
        }]
    ]
    payload = {
        "schema_version": 2,
        "tool_count": len(entries),
        "profiles": profiles,
        "profile_aliases": PROFILE_ALIASES,
        "tools": entries,
    }
    (root / "catalog.json").write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    (root / "TOOLS.md").write_text(markdown(entries), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
